### ISSUE TITLE
No config option for using default enderman model.

### ISSUE THREAD

**Issue by Bosskiller2001** [bonsaistudi0s/Enderman-Overhaul#12]
Looking at code, it seems there is supposed to be one but it doesn't generate, only the regular config does.

**Comment by AlexNijjar** [comment]
the client config is separe from the common config

https://github.com/bonsaistudi0s/EndermanOverhaul/blob/main/common/src/main/java/tech/alexnijjar/endermanoverhaul/client/config/EndermanOverhaulClientConfig.java

**Comment by Bosskiller2001** [comment]
This config file does not generate. I only have endermanoverhaul.toml

**Comment by AlexNijjar** [comment]
Oh. I'm having it generate fine on 1.20.1 on both forge and fabric. What version are you on?

**Comment by Bosskiller2001** [comment]
1.19.2 forge

**Comment by AlexNijjar** [comment]
[endermanoverhaul-forge-1.19.2-0.0.2.jar.zip](https://github.com/bonsaistudi0s/Enderman-Overhaul/files/12908246/endermanoverhaul-forge-1.19.2-0.0.2.jar.zip)
Can you give this version a shot?

**Comment by Bosskiller2001** [comment]
That version works

**Comment by AlexNijjar** [comment]
Jar above works then
