### ISSUE TITLE
[Bug]: Game Crashes on startup, and also crashes when trying to ingame config, creeper overhaul mod

### ISSUE THREAD

**Issue by Minebrah** [bonsaistudi0s/Enderman-Overhaul#13]
### Bug Description

https://gist.github.com/Minebrah/a7c78426c12f49bc4b8b9de159895a53

### How to Reproduce?

install endermanoverhaul-forge-1.19.2-0.0.1
Start up minecrash
Crash
Go back to main menu
Try to config other mod: Creeper overhaul
Click config button
Crash

### Expected Behavior

Not Crash

### Version

0.01

### Mod Loader Version

1.19.2

### Logs or additional context

I just read the last part. I DO have optifine installed. I've never had a problem running any of your mods with optifine installed until now. If you choose not to look into this issue I'll understand, its your call. thank you

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Minebrah** [comment]
Just to clarify I removed Traveler's backpack and my game is running smoothly with enderman overhaul and optifine installed. So the mod works with optifine, but has some incompatibility with Traveler's backpack.

**Comment by AlexNijjar** [comment]
yeah remove travelers backpack. it's their issue. or update to neoforge 1.20.4
