### ISSUE TITLE
[Bug]: Almost no EO Endermen spawn when Betterend is installed

### ISSUE THREAD

**Issue by lxly9** [bonsaistudi0s/Enderman-Overhaul#16]
### Bug Description

As the title states, Enderman Overhaul endermen do not spawn at all in Betterend biomes and almost none at all on the main end island. The same issue goes for Betternether with the nether enderman variants.

### How to Reproduce?

1. Install enderman overhaul
2. install betterend
3. go to the end
4. almost no eo endermen

### Expected Behavior

no vanilla endermen should spawn, instead enderman overhaul endermen

### Version

1.0.1

### Mod Loader Version

1.20.1 - QFAPI 7.4.0+0.90.0-1.20.1

### Mod Loader

Quilt

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by lxly9** [comment]
I have searched for an allow list of biomes in the config but it doesnt seem to exist. Ive also looked through bclib and betterend's config to disable endermen from spawning, but theres no option for that.

**Comment by Ricenami** [comment]
I am having the same problem, the minecraft enderman and the enderman from mobZ spawn everywhere. As for enderman overhaul, every 50 enderman I see an enderman. I'm having this issue in 1.19.2.

**Comment by AlexNijjar** [comment]
Can you give it a try in the latest version? I've added them to some additional end biome tags.
