### ISSUE TITLE
[Feature Request]: Datapack/Config Support for changing enderman spawn weights

### ISSUE THREAD

**Issue by Ricenami** [bonsaistudi0s/Enderman-Overhaul#19]
### Is your feature request related to a problem?

Hi! I love your mod, but I don't see the endermans often, and I see the default enderman a lot more than the different types of enderman, is there any way I could modify the spawn weights via datapack or config?

Cheers!

### Mod Version

1.19.2

### Mod Loader Version

Latest Fabric

### Mod Loader

Fabric

**Comment by morceaudebois** [comment]
Can confirm, new endermen are way too rare in my experience :(

**Comment by AlexNijjar** [comment]
This is something fabric or some other mod needs to do. I am not interested in implementing this.
