### ISSUE TITLE
[Bug]: Crash when killed by savanna enderman

### ISSUE THREAD

**Issue by RichPrune** [bonsaistudi0s/Enderman-Overhaul#22]
### Bug Description

Friend was killed by savanna enderman while being attacked by a group of mobs

### How to Reproduce?

1. Fight the mobs they fought
2. Die
3. Hard crash

### Expected Behavior

Not crash

### Version

1.19.2

### Mod Loader Version

forge latest for 1.19.2

### Mod Loader

Forge

### Logs or additional context

[latest (1).log](https://github.com/bonsaistudi0s/Enderman-Overhaul/files/13309867/latest.1.log)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by RichPrune** [comment]
could be similar to this issue, but wasn't sure so I posted anyway https://github.com/bonsaistudi0s/Enderman-Overhaul/issues/17

**Comment by RichPrune** [comment]
[crash-2023-11-09_09.53.03-client.txt](https://github.com/bonsaistudi0s/Enderman-Overhaul/files/13314446/crash-2023-11-09_09.53.03-client.txt)
this is the crash log btw

**Comment by AlexNijjar** [comment]
Update Entity Culling
