### ISSUE TITLE
[Bug]: Crash In server

### ISSUE THREAD

**Issue by rainysux** [bonsaistudi0s/Enderman-Overhaul#24]
### Bug Description

https://pastebin.com/TetRw10n
Crashes on server, used to not

### How to Reproduce?

Run mod on server 

### Version

1.0.2

### Mod Loader Version

1.20.1, 47.1.3

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
see https://github.com/bonsaistudi0s/Enderman-Overhaul/issues/25#issuecomment-1825082053
