### ISSUE TITLE
[Bug]: My game doesn't launch 

### ISSUE THREAD

**Issue by KAARVAAH** [bonsaistudi0s/Enderman-Overhaul#25]
### Bug Description

as the title says it doesn't launch when I try to and I got this:
![image](https://github.com/bonsaistudi0s/Enderman-Overhaul/assets/150563243/f9a52c25-9bc0-46da-9af8-013ba6651583)
someone could help me please?

### How to Reproduce?

1. I try to launch the game
2. It give me error explained in the fabric window and the game doesn't launch

### Expected Behavior

I expected that I could launch and play the game.

### Version

1.0.2

### Mod Loader Version

1.20.1 - 0.14.24

### Mod Loader

Fabric

### Logs or additional context

here is the log:
https://mclo.gs/tY8iOdH

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Dobbi124** [comment]
I am having the same issue after updating the mod to its newest version, this error is also on **Forge**, not just Fabric

**Comment by AlexNijjar** [comment]
weird, will check it out

**Comment by ZiLenTz** [comment]
Same here.
My server log: https://mclo.gs/t7fcDZW

**Comment by AlexNijjar** [comment]
so the issue was that somehow the autopublishing broke and renamed one of the files `endermanoverhaul-common.mixins.json` to `EndermanOverhaul-common.json`. No idea how that's happening and I don't know how to fix it so I've just manually uploaded the versions

https://modrinth.com/mod/enderman-overhaul/version/bfk8ik9k
https://modrinth.com/mod/enderman-overhaul/version/1.0.3

**Comment by KAARVAAH** [comment]
I updated to version 1.0.3and now works. Thanks for the support :D
