### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by BioTechproject27** [bonsaistudi0s/Enderman-Overhaul#28]
### Solution(s)

Is there any way to remove/modify some pearls without having to disable the specific enderman? E.g. would giving a custom loottable work?
Is there any documentation on e.g. spawning conditions and all the types of enderman, other entities like the scarab, spirit and ender_bullet, or the new items?

### Mod Version

1.0.3

### Mod Loader Version

1.20.1 - 0.14.24

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
- there's no config option. but yeah you can just edit the loot table in a datapack.
- scarabs only summoned by the desert enderman
- same with the spirits. they don't spawn naturally and only are summed by the soulsand enderman
- ender bullet is a projectile
there's no documentation but you can check out the biome modifiers if you want to see where they spawn https://github.com/bonsaistudi0s/Enderman-Overhaul/tree/main/forge/src/main/resources/data/endermanoverhaul/forge/biome_modifier

**Comment by BioTechproject27** [comment]
Ah, it would be great if a wiki existed.
Including things like their spawning conditions, behavior, what these other entities do, etc.
