### ISSUE TITLE
[Bug]: Start up crash

### ISSUE THREAD

**Issue by rainysux** [bonsaistudi0s/Enderman-Overhaul#30]
### Bug Description

Happens occassionally, sometimes in a row, sometimes not not sure what is causing it.

### Version

1.0.3

### Mod Loader Version

1.20.1, 47.1.3

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/izQNtw6r

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Run the world again
