### ISSUE TITLE
[Bug]: Proper spawning, but no animations

### ISSUE THREAD

**Issue by nb117** [bonsaistudi0s/Enderman-Overhaul#31]
### Bug Description

The endermen spawn in the proper locations perfectly but the same thing happens to them just like the modded creepers, no animations. All the needed software is downloaded too, if there's an order to it I'm not sure, but if anyone has any bits of info on it I'd love to know. I'm using Fabric as the mod loader if that helps narrows things down.

### Version

1.0.3

### Mod Loader Version

1.20.1 0.15

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ItzNatsu** [comment]
This might be related to iris as there's currently a bug that breaks animations on many mods. try the animations without shaders enabled.

**Comment by AlexNijjar** [comment]
Yeah, not something I can fix. I believe turning off shadows in your shader settings fixes is.
