### ISSUE TITLE
[Feature Request]: Add configurable cooldown to hostile teleportation

### ISSUE THREAD

**Issue by aszecsei** [bonsaistudi0s/Enderman-Overhaul#34]
### Is your feature request related to a problem?

It's particularly annoying when an entire crowd of end endermen ping-pong teleport me around the map.

### Solution(s)

It'd be nice to have some sort of player-side cooldown preventing hostile teleportation immediately following a hostile teleport.

### Describe alternatives you've considered

An item or effect to prevent hostile teleportation (or just reduce the range/likelihood of it?) could also help to feel like there's something that can be done to prepare for a fight in the end.

### Mod Version

1.0.3

### Mod Loader Version

1.20.1 - 47.1.84

### Mod Loader

NeoForge

**Comment by AlexNijjar** [comment]
A cooldown system would be a little annoying to manage for each player. But I've added a config to change the teleport chance, with a default of 50%.
